name: Build and push

on:
  workflow_dispatch:
    inputs:
      image_version:
        required: true
        type: string
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/docker_image_build.yml
    with:
      push: true
      image_version: ${{ github.event_name == 'push' && github.ref_type == 'tag' ? github.ref_name : github.event.inputs.image_version }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
