name: Build test

on:
  pull_request:
    paths:
      - .github/workflows/build-test.yml
      - .github/workflows/docker_image_build.yml
      - docker/**/*

jobs:
  build:
    uses: ./.github/workflows/docker_image_build.yml
    with:
      image_version: ${{ github.sha}}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
