name: Docker image build

on:
  workflow_call:
    inputs:
      push:
        default: false
        type: boolean
      mruby-version:
        default: 'master'
        type: string
    secrets:
      dockerhub_username:
        required: true
      dockerhub_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
      - uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ inputs.push }}
          tags: ${{ secrets.dockerhub_username }}/mruby-build:${{ inputs.mruby-version }}
          build-args: |
            MRUBY_VERSION=${{ inputs.mruby-version }}
